#!/usr/bin/env bash
#
# build-pi5-image.sh — assemble an SD-card-ready Aegis boot directory for
# Raspberry Pi 5.
#
# This script produces `build/pi5-image/` containing every file the user
# needs to copy to the root of a freshly-formatted FAT32 SD card. It does
# NOT touch any block devices, does not need root, and is safe to run on
# any developer machine with network access.
#
# Prerequisites:
#   make -C kernel/arch/arm64 image    # produces kernel/arch/arm64/build/aegis.img
#
# Usage:
#   bash tools/build-pi5-image.sh
#
# Output:
#   build/pi5-image/
#     bcm2712-rpi-5-b.dtb     Pi 5 device tree (firmware auto-selects this)
#     bcm2712d0.dtbo          optional overlay for BCM2712 D0 stepping (rev 1.1 boards)
#     config.txt              Aegis boot config
#     kernel_2712.img         renamed copy of build/aegis.img (Pi 5 canonical name)
#
# Pi 5 does NOT use bootcode.bin / start*.elf / fixup*.dat from the SD card —
# that second-stage bootloader lives entirely in the on-board SPI EEPROM. The
# SoC boot ROM reads the EEPROM, which runs TF-A BL31 at EL3 and then hands
# control to the kernel at EL2. The SD card only needs: DTB + kernel + config.
#
# Firmware blobs are cached in references/pi-firmware/ so repeat runs are
# offline after the first fetch.
#
# STATUS: Pi 5 hardware boot is UNTESTED as of 2026-04-12. Debug UART on
# BCM2712 is at physical 0x107D001000 and is exposed on the 3-pin JST-SH
# header between the two micro-HDMI connectors — NOT on GPIO 14/15 (those
# route through the RP1 south bridge which we don't have a driver for).

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
KERNEL_IMG="$REPO/kernel/arch/arm64/build/aegis.img"
FIRMWARE_CACHE="$REPO/references/pi-firmware"
OUT_DIR="$REPO/build/pi5-image"
FIRMWARE_BASE="https://github.com/raspberrypi/firmware/raw/master/boot"

# Required files — the build fails if any of these can't be fetched.
FIRMWARE_FILES=(
    bcm2712-rpi-5-b.dtb
)

# Optional files — fetched best-effort; missing ones just get skipped.
# bcm2712d0.dtbo is the overlay for BCM2712 D0 stepping (Pi 5 rev 1.1 boards,
# including the 2GB and 16GB SKUs). Harmless on older C-stepping silicon.
FIRMWARE_OPTIONAL=(
    overlays/bcm2712d0.dtbo
)

# ── 1. Sanity check ──────────────────────────────────────────────────
if [ ! -f "$KERNEL_IMG" ]; then
    cat >&2 <<EOF
error: $KERNEL_IMG not found.

Build the ARM64 kernel image first:

    make -C kernel/arch/arm64 image

That produces build/aegis-arm64.elf and then wraps it in the Linux arm64
Image format as build/aegis.img. This script copies the result into the
Pi 5 boot directory as kernel_2712.img.
EOF
    exit 1
fi

# ── 2. Fetch firmware (cache in references/pi-firmware/) ─────────────
mkdir -p "$FIRMWARE_CACHE"

fetch_one() {
    local rel="$1"
    local dest="$FIRMWARE_CACHE/$rel"
    mkdir -p "$(dirname "$dest")"
    if [ ! -s "$dest" ]; then
        echo ">>> downloading $rel ..."
        if ! curl -L -f -o "$dest.tmp" "$FIRMWARE_BASE/$rel"; then
            rm -f "$dest.tmp"
            return 1
        fi
        mv "$dest.tmp" "$dest"
    fi
    [ -s "$dest" ]
}

for f in "${FIRMWARE_FILES[@]}"; do
    if ! fetch_one "$f"; then
        cat >&2 <<EOF
error: failed to download $f from
  $FIRMWARE_BASE/$f

Check network connectivity and retry. If GitHub is unreachable you can
manually download the file from the upstream repo and drop it in:
  $FIRMWARE_CACHE/$f
then re-run this script.
EOF
        exit 1
    fi
done

for f in "${FIRMWARE_OPTIONAL[@]}"; do
    if ! fetch_one "$f"; then
        echo ">>> note: optional file $f not fetched; skipping"
    fi
done

# ── 3. Produce build/pi5-image/ ──────────────────────────────────────
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

# DTB always goes at the root of the FAT32 partition.
cp "$FIRMWARE_CACHE/bcm2712-rpi-5-b.dtb" "$OUT_DIR/"

# Optional overlay: Pi firmware looks for overlays/ on the boot partition.
if [ -s "$FIRMWARE_CACHE/overlays/bcm2712d0.dtbo" ]; then
    mkdir -p "$OUT_DIR/overlays"
    cp "$FIRMWARE_CACHE/overlays/bcm2712d0.dtbo" "$OUT_DIR/overlays/"
fi

cat > "$OUT_DIR/config.txt" <<'CFG'
# Aegis Pi 5 boot config (generated by tools/build-pi5-image.sh)
#
# kernel=kernel_2712.img
#   Canonical Pi 5 kernel filename. The Pi 5 firmware looks for this name
#   by default; kernel8.img also works as a backward-compatible fallback.
#
# kernel_address=0x40200000
#   Physical address at which the firmware loads the kernel image. Our
#   linker.ld pins KERN_LMA = 0x40200000, so we load there directly. The
#   Pi firmware accepts any 32-bit physical address within the first 4 GB.
#   Pi 5 RAM base is 0x00000000 (not 0x40000000 like Pi 4), so 0x40200000
#   is a valid RAM address on any Pi 5 SKU (minimum 4 GB).
#
# enable_uart=1
#   Enables and pre-initializes the BCM2712 internal PL011 debug UART
#   (physical 0x107D001000) at 115200 baud from a 48 MHz reference clock.
#   This UART is exposed on the 3-pin JST-SH "UART" header between the
#   two micro-HDMI ports — NOT on GPIO 14/15. GPIO 14/15 is routed through
#   the RP1 south bridge which we do not yet have a driver for.
#
# os_check=0
#   Suppresses the firmware warning "This OS does not indicate support
#   for Raspberry Pi 5" that would otherwise be printed over the debug
#   UART before our kernel runs. We know what we're doing.
#
# pciex4_reset=0
#   Do NOT reset the PCIe x4 controller at OS handoff. RP1 hangs off this
#   PCIe link, and resetting it leaves RP1 in an indeterminate state.
#   Leaving it alone keeps RP1 in whatever state the EEPROM left it so a
#   future RP1 driver has a clean starting point.
#
# No arm_64bit, device_tree, uart_2ndstage, disable_commandline_tags:
#   - arm_64bit: ignored on Pi 5 (Cortex-A76 is AArch64-only).
#   - device_tree: Pi 5 firmware auto-selects bcm2712-rpi-5-b.dtb; don't
#     override or it breaks D0-stepping overlay loading.
#   - uart_2ndstage: that's for the RP1 UART path (GPIO 14/15). Irrelevant
#     to the BCM2712 internal debug UART we're actually using.
#   - disable_commandline_tags: not needed; we don't consume firmware args.
kernel=kernel_2712.img
kernel_address=0x40200000
enable_uart=1
os_check=0
pciex4_reset=0
CFG

cp "$KERNEL_IMG" "$OUT_DIR/kernel_2712.img"

# ── 4. Summary + flash instructions ──────────────────────────────────
SIZE="$(du -sh "$OUT_DIR" | awk '{print $1}')"

cat <<EOF

================================================================
Aegis Pi 5 boot image ready: $OUT_DIR ($SIZE)
================================================================

Contents:
$(cd "$OUT_DIR" && find . -type f | sed 's|^\./|  |')

To flash to an SD card:

  1. Format an SD card as FAT32 (single partition covering the card).
     macOS:
       diskutil eraseDisk FAT32 AEGISBOOT MBRFormat /dev/diskN
     Linux:
       sudo parted /dev/sdX mklabel msdos
       sudo parted /dev/sdX mkpart primary fat32 1MiB 100%
       sudo mkfs.vfat -F 32 -n AEGISBOOT /dev/sdX1

  2. Copy every file from $OUT_DIR/ to the root of the SD card
     (preserving the overlays/ subdirectory if present):
       cp -rv $OUT_DIR/* /Volumes/AEGISBOOT/         # macOS
       cp -rv $OUT_DIR/* /mnt/aegisboot/ && sync     # Linux

  3. Eject the SD card cleanly and insert it into the Pi 5.

  4. Connect a debug cable to the Pi 5's 3-pin JST-SH "UART" header.
     This header sits between the two micro-HDMI ports on the board
     edge — it is silkscreened "UART". It is NOT the 40-pin GPIO header.

     Recommended cable: Raspberry Pi Debug Probe (\$12, first-party)
       https://www.raspberrypi.com/products/debug-probe/
     It plugs directly into the JST-SH header and presents as a USB CDC
     serial device on the laptop.

     Alternatives: Adafruit #5054 (JST-SH 3-pin cable) + any USB-TTL
     adapter you already own; or a generic JST-SH-to-Dupont jumper set.

     NOTE: A plain 40-pin GPIO serial cable (e.g. Adafruit #954) will
     NOT work on Pi 5. GPIO 14/15 on the 40-pin header is routed through
     the RP1 south bridge, which requires a PCIe + RP1 driver we don't
     have yet. The JST-SH header is the only working debug UART path.

  5. Open a serial terminal at 115200 8N1:
       macOS:  screen /dev/tty.usbmodem* 115200       (Debug Probe)
               screen /dev/tty.usbserial-* 115200     (USB-TTL adapter)
       Linux:  screen /dev/ttyACM0 115200             (Debug Probe)
               screen /dev/ttyUSB0 115200             (USB-TTL adapter)

  6. Power the Pi 5 (USB-C). You should see:

       [BOOT] aegis arm64 (pre-MMU)
       [SERIAL] OK: PL011 UART initialized
       [PMM] OK: ...
       [GIC] OK: GICv2 initialized        <-- Pi 5 uses GIC-400 (GICv2)
       [TIMER] OK: ...
       [SCHED] OK: scheduler started, N tasks

Notes:
  - Pi 5 hardware boot is UNTESTED as of 2026-04-12.
  - Firmware blobs are cached in $FIRMWARE_CACHE
    so subsequent runs are offline.
  - The SD card only carries DTB + kernel + config.txt. Pi 5's second-
    stage bootloader lives in the on-board SPI EEPROM, not on the SD.

EOF
