#include "proc.h"
#include "elf.h"
#include "vmm.h"
#include "pmm.h"
#include "arch.h"
#include "printk.h"
#include <stdint.h>
#include <stddef.h>

/*
 * init_elf / init_elf_len — generated by:
 *   cd user/init && xxd -i init.elf > init_bin.c
 * which produces exactly these symbol names when invoked as "xxd -i init.elf".
 */
extern const unsigned char init_elf[];
extern const unsigned int  init_elf_len;

/* 16KB kernel stack for the user process (4 pages, contiguous via PMM assumption) */
#define STACK_PAGES 4
#define STACK_SIZE  (STACK_PAGES * 4096UL)

/*
 * User stack layout:
 *   top = USER_STACK_TOP  (= 0x7FFFFFFF000, 16-byte aligned)
 *   page = [USER_STACK_PAGE, USER_STACK_TOP)
 * 0x7FFFFFFF000 ends in 0x000 — 4096-byte aligned → 16-byte aligned. ✓
 * Per AMD64 ABI, RSP on entry to _start must be 16-byte aligned.
 */
#define USER_STACK_TOP  0x7FFFFFFF000ULL
#define USER_STACK_PAGE (USER_STACK_TOP - 4096ULL)

/* Exported from syscall_entry.asm — a bare iretq, NOT a C function.
 * proc_spawn uses its address only as a return-address slot in the
 * initial kernel stack frame. */
extern void proc_enter_user(void);

void
proc_spawn(const uint8_t *elf_data, size_t elf_len)
{
    /* Allocate process control block (one PMM page) */
    uint64_t tcb_phys = pmm_alloc_page();
    if (!tcb_phys) {
        printk("[PROC] FAIL: OOM allocating process TCB\n");
        for (;;) {}
    }
    aegis_process_t *proc = (aegis_process_t *)(uintptr_t)tcb_phys;

    /* Allocate kernel stack (STACK_PAGES contiguous pages — see PMM
     * contiguity assumption in sched_spawn) */
    uint8_t *kstack = (void *)0;
    uint32_t i;
    for (i = 0; i < STACK_PAGES; i++) {
        uint64_t p = pmm_alloc_page();
        if (!p) {
            printk("[PROC] FAIL: OOM allocating kernel stack\n");
            for (;;) {}
        }
        if (i == 0)
            kstack = (uint8_t *)(uintptr_t)p;
    }

    /* Create per-process page tables (kernel high entries shared) */
    proc->pml4_phys = vmm_create_user_pml4();

    /* Load ELF into the user address space */
    uint64_t entry_rip = elf_load(proc->pml4_phys, elf_data, elf_len);
    if (!entry_rip) {
        printk("[PROC] FAIL: ELF parse error\n");
        for (;;) {}
    }

    /* Allocate and map user stack page */
    uint64_t user_stack_phys = pmm_alloc_page();
    if (!user_stack_phys) {
        printk("[PROC] FAIL: OOM allocating user stack\n");
        for (;;) {}
    }
    vmm_map_user_page(proc->pml4_phys, USER_STACK_PAGE, user_stack_phys,
                      VMM_FLAG_USER | VMM_FLAG_WRITABLE);

    /*
     * Build initial kernel stack.
     *
     * ctx_switch pops: r15, r14, r13, r12, rbp, rbx, then ret.
     * The ret target is proc_enter_user (a bare iretq label).
     * iretq pops a ring-3 frame: RIP, CS, RFLAGS, RSP, SS.
     *
     * Stack layout from low (RSP) to high:
     *   [r15=0][r14=0][r13=0][r12=0][rbp=0][rbx=0]
     *   [proc_enter_user]
     *   [entry_rip][CS=0x23][RFLAGS=0x202][user_RSP][SS=0x1B]
     *
     * Push order (high-to-low, decrementing sp):
     *   SS first (highest address), r15 last (lowest = task.rsp value).
     */
    uint64_t *sp = (uint64_t *)(kstack + STACK_SIZE);

    *--sp = 0x1BULL;            /* SS  — user data | RPL=3      */
    *--sp = USER_STACK_TOP;     /* RSP — user stack top          */
    *--sp = 0x202ULL;           /* RFLAGS — IF=1, reserved bit 1 */
    *--sp = 0x23ULL;            /* CS  — user code | RPL=3       */
    *--sp = entry_rip;          /* RIP — ELF entry point         */

    *--sp = (uint64_t)(uintptr_t)proc_enter_user; /* ret → iretq */
    *--sp = 0;                  /* rbx */
    *--sp = 0;                  /* rbp */
    *--sp = 0;                  /* r12 */
    *--sp = 0;                  /* r13 */
    *--sp = 0;                  /* r14 */
    *--sp = 0;                  /* r15 ← task.rsp */

    /* Initialize task fields */
    proc->task.rsp              = (uint64_t)(uintptr_t)sp;
    proc->task.stack_base       = kstack;
    proc->task.kernel_stack_top = (uint64_t)(uintptr_t)(kstack + STACK_SIZE);
    proc->task.tid              = 0xFF;   /* fixed user-process TID for Phase 5 */
    proc->task.is_user          = 1;

    sched_add(&proc->task);
}

void
proc_spawn_init(void)
{
    proc_spawn(init_elf, (size_t)init_elf_len);
}
