#ifndef AEGIS_PROC_H
#define AEGIS_PROC_H

#include "sched.h"
#include "vfs.h"
#include "fd_table.h"
#include "cap.h"
#include "signal.h"
#include "vma.h"
#include "spinlock.h"
#include <stdint.h>
#include <stddef.h>

#define MMAP_FREE_MAX 64

typedef struct {
    uint64_t base;
    uint64_t len;
} mmap_free_t;

/*
 * aegis_process_t — user process control block.
 *
 * task MUST be the first member: the scheduler stores all tasks as
 * aegis_task_t * pointers. When task.is_user == 1, the scheduler casts
 * the pointer to aegis_process_t * to reach pml4_phys. This cast is
 * safe only because task is at offset 0 (guaranteed by this layout).
 * Never use this cast when is_user == 0 — kernel tasks are not
 * aegis_process_t instances and the memory past the aegis_task_t fields
 * is unrelated.
 */
typedef struct aegis_process {
    aegis_task_t  task;                    /* MUST be first — scheduler casts to aegis_task_t * */
    uint64_t      pml4_phys;              /* physical address of this process's PML4 */
    fd_table_t   *fd_table;               /* shared, refcounted fd table (Phase 29) */
    cap_slot_t    caps[CAP_TABLE_SIZE];   /* Phase 11 — capability table */
    uint32_t      authenticated;          /* 1 if session passed login auth; survives exec */
    uint64_t      brk;                    /* current heap limit (user VA); grows up */
    uint64_t      brk_base;               /* initial brk (ELF end); shrink floor */
    uint64_t      mmap_base;              /* next anonymous mmap VA; bump allocator */
    mmap_free_t   mmap_free[MMAP_FREE_MAX]; /* VA freelist for munmap→mmap reuse */
    uint32_t      mmap_free_count;          /* number of entries in mmap_free[]  */
    spinlock_t    mmap_free_lock;           /* M2: guards mmap_free[] for CLONE_VM threads on SMP */
    vma_entry_t  *vma_table;              /* kva-allocated VMA table; NULL until vma_init */
    uint32_t      vma_count;              /* number of valid VMA entries */
    uint32_t      vma_capacity;           /* max entries (170 per kva page) */
    uint32_t      vma_refcount;           /* 1 = sole owner; >1 = shared (CLONE_VM) */
    char          exe_path[256];          /* binary path, set at execve */
    uint32_t      pid;          /* unique process ID; 1 = init */
    uint32_t      tgid;         /* thread group ID (= leader's PID) */
    uint32_t      thread_count; /* live threads in this group (leader tracks) */
    uint32_t      ppid;         /* parent PID; 0 = no parent   */
    uint32_t      uid;          /* user ID; 0 = root */
    uint32_t      gid;          /* group ID; 0 = root */
    uint32_t      pgid;         /* process group ID; init = own pid      */
    uint32_t      sid;          /* session ID; == pid for session leaders */
    uint32_t      umask;        /* file creation mask; init = 022        */
    uint32_t      stop_signum;  /* signal that caused TASK_STOPPED; 0 = not stopped */
    char          cwd[256];     /* current working directory; init = "/" */
    uint64_t      exit_status;  /* lower 8 bits = exit code; written before zombie */
    /* Phase 17 — signal subsystem */
    uint64_t      pending_signals;   /* bitmask; bit N = signal N pending */
    uint64_t      signal_mask;       /* blocked signals; 0 = nothing blocked */
    k_sigaction_t sigactions[64];    /* per-signal handler/mask/flags */
} aegis_process_t;

/* Allocate and return the next unique process ID (monotonically increasing). */
uint32_t proc_alloc_pid(void);

/* Load elf_data into a new user process and add it to the scheduler run queue.
 * Called from kernel_main before sched_start. */
void proc_spawn(const uint8_t *elf_data, size_t elf_len);

/* Convenience wrapper: spawn the embedded init binary (init_elf / init_elf_len).
 * These symbols are generated by xxd in user/init/init_bin.c. */
void proc_spawn_init(void);

/* Find a user process by PID. Walks the scheduler circular task list.
 * Returns NULL if no matching process found. */
aegis_process_t *proc_find_by_pid(uint32_t pid);

#endif /* AEGIS_PROC_H */
