#ifndef AEGIS_PROC_H
#define AEGIS_PROC_H

#include "sched.h"
#include "vfs.h"
#include "cap.h"
#include <stdint.h>
#include <stddef.h>

/*
 * aegis_process_t — user process control block.
 *
 * task MUST be the first member: the scheduler stores all tasks as
 * aegis_task_t * pointers. When task.is_user == 1, the scheduler casts
 * the pointer to aegis_process_t * to reach pml4_phys. This cast is
 * safe only because task is at offset 0 (guaranteed by this layout).
 * Never use this cast when is_user == 0 — kernel tasks are not
 * aegis_process_t instances and the memory past the aegis_task_t fields
 * is unrelated.
 */
typedef struct {
    aegis_task_t  task;                    /* MUST be first — scheduler casts to aegis_task_t * */
    uint64_t      pml4_phys;              /* physical address of this process's PML4 */
    vfs_file_t    fds[PROC_MAX_FDS];      /* Phase 10 — ops==NULL means slot free */
    cap_slot_t    caps[CAP_TABLE_SIZE];   /* Phase 11 — capability table */
    uint64_t      brk;                    /* current heap limit (user VA); grows up */
    uint64_t      mmap_base;              /* next anonymous mmap VA; bump allocator */
    uint64_t      fs_base;                /* FS segment base for TLS; set by arch_prctl */
    uint32_t      pid;          /* unique process ID; 1 = init */
    uint32_t      ppid;         /* parent PID; 0 = no parent   */
    char          cwd[256];     /* current working directory; init = "/" */
    uint64_t      exit_status;  /* lower 8 bits = exit code; written before zombie */
} aegis_process_t;

/* Allocate and return the next unique process ID (monotonically increasing). */
uint32_t proc_alloc_pid(void);

/* Load elf_data into a new user process and add it to the scheduler run queue.
 * Called from kernel_main before sched_start. */
void proc_spawn(const uint8_t *elf_data, size_t elf_len);

/* Convenience wrapper: spawn the embedded init binary (init_elf / init_elf_len).
 * These symbols are generated by xxd in user/init/init_bin.c. */
void proc_spawn_init(void);

#endif /* AEGIS_PROC_H */
