#include "proc.h"
#include "elf.h"
#include "vmm.h"
#include "pmm.h"
#include "kva.h"
#include "printk.h"
#include "arch.h"
#include "console.h"
#include "kbd_vfs.h"
#include <stdint.h>
#include <stddef.h>

static uint32_t s_next_pid = 1;

uint32_t
proc_alloc_pid(void)
{
    return s_next_pid++;
}

_Static_assert(offsetof(aegis_process_t, task) == 0,
               "aegis_process_t: task must be at offset 0 for safe cast");

/*
 * init_elf / init_elf_len — generated by the Makefile's $(INIT_BIN_C) rule:
 *   xxd -i <init>.elf | sed "s/<init>_elf/init_elf/g" > kernel/init_bin.c
 * Symbols are renamed to init_elf regardless of whether INIT=hello or INIT=shell.
 */
extern const unsigned char init_elf[];
extern const unsigned int  init_elf_len;

/* 4KB kernel stack for the user process (single page) */
#define STACK_SIZE  4096UL

/*
 * User stack layout:
 *   top = USER_STACK_TOP  (= 0x7FFFFFFF000, 16-byte aligned)
 *   page = [USER_STACK_PAGE, USER_STACK_TOP)
 * 0x7FFFFFFF000 ends in 0x000 — 4096-byte aligned → 16-byte aligned. ✓
 * Per AMD64 ABI, RSP on entry to _start must be 16-byte aligned.
 */
#define USER_STACK_TOP  0x7FFFFFFF000ULL
#define USER_STACK_PAGE (USER_STACK_TOP - 4096ULL)

/* Exported from syscall_entry.asm — a bare iretq, NOT a C function.
 * proc_spawn uses its address only as a return-address slot in the
 * initial kernel stack frame. */
extern void proc_enter_user(void);

void
proc_spawn(const uint8_t *elf_data, size_t elf_len)
{
    /* Allocate process control block (one kva page — higher-half VA). */
    aegis_process_t *proc = kva_alloc_pages(1);

    /* Allocate kernel stack (one kva page — per-process higher-half VA).
     * kva pages are mapped into pd_hi (shared with user PML4s), so this
     * stack VA is reachable regardless of which PML4 is loaded in CR3.
     * Each proc_spawn call gets a distinct VA; the single-KSTACK_VA
     * limitation from Phase 5 is now resolved. */
    uint8_t *kstack = kva_alloc_pages(1);

    /* Create per-process page tables (kernel high entries shared) */
    proc->pml4_phys = vmm_create_user_pml4();

    /* Load ELF into the user address space */
    elf_load_result_t er;
    if (elf_load(proc->pml4_phys, elf_data, elf_len, &er) != 0) {
        printk("[PROC] FAIL: ELF parse error\n");
        for (;;) {}
    }
    uint64_t entry_rip = er.entry;
    uint64_t brk_start = er.brk;

    /* Allocate and map user stack page.
     * vmm_zero_page ensures the initial stack contents are zero — without
     * this, PMM frames carry stale data.  musl's _start reads argc from
     * [rsp] immediately; a zero there means argc=0, which is correct for
     * a single-process system with no argv/envp. */
    uint64_t user_stack_phys = pmm_alloc_page();
    if (!user_stack_phys) {
        printk("[PROC] FAIL: OOM allocating user stack\n");
        for (;;) {}
    }
    vmm_zero_page(user_stack_phys);
    vmm_map_user_page(proc->pml4_phys, USER_STACK_PAGE, user_stack_phys,
                      VMM_FLAG_PRESENT | VMM_FLAG_USER | VMM_FLAG_WRITABLE);

    /*
     * Build initial kernel stack.
     *
     * ctx_switch pops: r15, r14, r13, r12, rbp, rbx, then ret.
     * The ret target is proc_enter_user (a bare iretq label).
     * iretq pops a ring-3 frame: RIP, CS, RFLAGS, RSP, SS.
     *
     * Stack layout from low (RSP) to high:
     *   [r15=0][r14=0][r13=0][r12=0][rbp=0][rbx=0]
     *   [proc_enter_user]
     *   [entry_rip][CS=0x23][RFLAGS=0x202][user_RSP][SS=0x1B]
     *
     * Push order (high-to-low, decrementing sp):
     *   SS first (highest address), r15 last (lowest = task.rsp value).
     */
    uint64_t *sp = (uint64_t *)(kstack + STACK_SIZE);

    *--sp = 0x1BULL;            /* SS  — user data | RPL=3       */
    *--sp = USER_STACK_TOP - 128; /* RSP — 128 bytes below top; stack page is zeroed,
                                   * so [rsp]=argc=0, [rsp+8]=argv[0]=NULL,
                                   * [rsp+16]=envp[0]=NULL, [rsp+24]=AT_NULL. */
    *--sp = 0x202ULL;           /* RFLAGS — IF=1, reserved bit 1  */
    *--sp = 0x23ULL;            /* CS  — user code | RPL=3        */
    *--sp = entry_rip;          /* RIP — ELF entry point          */

    /*
     * User PML4 physical address: popped by proc_enter_user before iretq.
     * proc_enter_user does: pop rax; mov cr3, rax; iretq.
     * This switches CR3 to the user PML4 while still on the higher-half
     * kernel stack (kva-allocated VA — accessible in both master and user
     * PML4, as kva pages live in pd_hi which is shared across all PML4s).
     *
     * We must switch CR3 here rather than before ctx_switch in sched_tick
     * because sched_tick runs on the outgoing task's kernel stack. Switching
     * to the user PML4 from that stack must not occur until we are on a stack
     * that is mapped in the user PML4.
     */
    *--sp = proc->pml4_phys;    /* user PML4 phys — popped by proc_enter_user */

    *--sp = (uint64_t)(uintptr_t)proc_enter_user; /* ret → CR3 switch + iretq */
    *--sp = 0;                  /* rbx */
    *--sp = 0;                  /* rbp */
    *--sp = 0;                  /* r12 */
    *--sp = 0;                  /* r13 */
    *--sp = 0;                  /* r14 */
    *--sp = 0;                  /* r15 ← task.rsp */

    /* Initialize task fields */
    proc->task.rsp              = (uint64_t)(uintptr_t)sp;
    proc->task.stack_base       = kstack;
    proc->task.kernel_stack_top = (uint64_t)(uintptr_t)(kstack + STACK_SIZE);
    proc->task.tid              = 0xFF;   /* fixed user-process TID for Phase 5 */
    proc->task.is_user          = 1;
    proc->task.stack_pages      = 1;

    /* Zero the fd table — all slots start as free (ops == NULL).
     * kva_alloc_pages does not zero pages; explicit init required. */
    {
        uint64_t i;
        for (i = 0; i < PROC_MAX_FDS; i++)
            proc->fds[i].ops = (const vfs_ops_t *)0;
    }

    /* Zero cap table — all slots start empty.
     * kva_alloc_pages maps raw physical frames without zeroing; the loop is
     * required to ensure all slots start as CAP_KIND_NULL (= 0).
     * Phase 10 is responsible for zeroing fds[] — this loop covers caps[] only. */
    {
        uint32_t ci;
        for (ci = 0; ci < CAP_TABLE_SIZE; ci++) {
            proc->caps[ci].kind   = CAP_KIND_NULL;
            proc->caps[ci].rights = 0;
        }
    }

    proc->pid              = proc_alloc_pid();   /* 1 for init */
    proc->ppid             = 0;
    proc->pgid             = proc->pid;
    proc->umask            = 022U;
    proc->stop_signum      = 0;
    proc->cwd[0]           = '/';
    proc->cwd[1]           = '\0';
    proc->exit_status      = 0;
    proc->pending_signals  = 0;
    proc->signal_mask      = 0;
    __builtin_memset(proc->sigactions, 0, sizeof(proc->sigactions));
    proc->task.state       = TASK_RUNNING;
    proc->task.waiting_for = 0;

    /* Grant initial capabilities to this user process.
     * cap_grant returns the slot index (>= 0) on success or -ENOCAP if the
     * table is full. With CAP_TABLE_SIZE = 8 and two grants, this cannot fail. */

    /* Grant open capability. */
    if (cap_grant(proc->caps, CAP_TABLE_SIZE,
                  CAP_KIND_VFS_OPEN, CAP_RIGHTS_READ) < 0) {
        printk("[CAP] FAIL: cap_grant VFS_OPEN returned -ENOCAP\n");
        for (;;) {}
    }

    /* Grant write capability. */
    if (cap_grant(proc->caps, CAP_TABLE_SIZE,
                  CAP_KIND_VFS_WRITE, CAP_RIGHTS_WRITE) < 0) {
        printk("[CAP] FAIL: cap_grant VFS_WRITE returned -ENOCAP\n");
        for (;;) {}
    }

    /* Grant read capability. */
    if (cap_grant(proc->caps, CAP_TABLE_SIZE,
                  CAP_KIND_VFS_READ, CAP_RIGHTS_READ) < 0) {
        printk("[CAP] FAIL: cap_grant VFS_READ returned -ENOCAP\n");
        for (;;) {}
    }

    /* Pre-open fd 1 (stdout) to the console device.
     * User process inherits stdout without a sys_open call. */
    proc->fds[1] = *console_open();

    /* Pre-open fd 0 (stdin) to keyboard device. */
    proc->fds[0] = *kbd_vfs_open();

    /* Pre-open fd 2 (stderr) to console device. */
    proc->fds[2] = *console_open();

    /* Initialise heap break to top of ELF segments. */
    proc->brk = brk_start;

    /* Initialise mmap bump allocator base (112 TB — safely above heap, below stack). */
    proc->mmap_base = 0x0000700000000000ULL;

    /* FS base starts at zero; arch_prctl(ARCH_SET_FS) sets it at musl startup. */
    proc->fs_base = 0;

    printk("[CAP] OK: 3 capabilities granted to init\n");

    sched_add(&proc->task);
}

void
proc_spawn_init(void)
{
    proc_spawn(init_elf, (size_t)init_elf_len);
}
