#ifndef AEGIS_PROC_H
#define AEGIS_PROC_H

#include "sched.h"
#include <stdint.h>
#include <stddef.h>

/*
 * aegis_process_t — user process control block.
 *
 * task MUST be the first member: the scheduler stores all tasks as
 * aegis_task_t * pointers. When task.is_user == 1, the scheduler casts
 * the pointer to aegis_process_t * to reach pml4_phys. This cast is
 * safe only because task is at offset 0 (guaranteed by this layout).
 * Never use this cast when is_user == 0 — kernel tasks are not
 * aegis_process_t instances and the memory past the aegis_task_t fields
 * is unrelated.
 */
typedef struct {
    aegis_task_t task;      /* MUST be first — scheduler casts to aegis_task_t * */
    uint64_t     pml4_phys; /* physical address of this process's PML4 */
} aegis_process_t;

/* Load elf_data into a new user process and add it to the scheduler run queue.
 * Called from kernel_main before sched_start. */
void proc_spawn(const uint8_t *elf_data, size_t elf_len);

/* Convenience wrapper: spawn the embedded init binary (init_elf / init_elf_len).
 * These symbols are generated by xxd in user/init/init_bin.c. */
void proc_spawn_init(void);

#endif /* AEGIS_PROC_H */
